name: Release
on:
  release:
    types: [created]
env:
  BUILD_TYPE: Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev liblapack-dev libarpack2-dev libsuperlu-dev
          bash lib.sh
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/build/bin/varGWAS